name: flutter_playground
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  oauth2: ^2.0.0
  flutter_secure_storage: ^4.2.0
  dartz: ^0.10.0-nullsafety.2
  dio: ^4.0.0
  freezed_annotation: ^0.14.3
  webview_flutter: ^2.0.13
  flash: ^2.0.1
  auto_route: ^2.2.0
  logger: ^1.1.0
  flutter_riverpod: ^1.0.0-dev.7
  material_design_icons_flutter: ^5.0.5955-rc.1
  json_annotation: ^4.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.5
  freezed: ^0.14.2
  auto_route_generator: ^2.1.0
  flutter_lints: ^1.0.4
  json_serializable: ^5.0.2



flutter:
  uses-material-design: true

